version: "3.4"

services:
  testapp-dev:
    image: docker.themarker.com:8083/testapp:${version:-latest}
    #image: maozzadok/testapp:${version:-latest}
    build: .
    networks:
      - development
    environment:
      - version=${version:-latest}
    ports:
      - "3112:3112"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3112"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
          replicas: 5
          update_config:
            parallelism: 2
            delay: 10s
            order: start-first
          restart_policy:
            condition: on-failure
networks:
  development:
    external: true
