version: "3.4"

services:
  testapp-dev:
    image: nexus-ng.themarker.com/testapp:${version:-latest}
    #image: maozzadok/testapp:${version:-latest}
    build: .
    networks:
      - prod02
    environment:
      - version=${version:-latest}
    ports:
      - "3112:3112"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3112"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
          replicas: 5
          update_config:
            parallelism: 5
            delay: 30s
            order: start-first
          restart_policy:
            condition: on-failure
networks:
  prod02:
    external: true